language: cpp
matrix:
  include:
    # mac_cmake
    - os: osx
      env: BUILD_TARGET=mac_cmake
      osx_image: xcode11.6
    # iOS_cmake
    - os: osx
      env: BUILD_TARGET=ios_cmake
      osx_image: xcode11.6
    # android cmake
    - os: linux
      env: BUILD_TARGET=android_cmake
    # android_lua cmake
    #- os: linux
    #  env: BUILD_TARGET=android_lua_cmake
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-6
    #- os: linux
    #  env: BUILD_TARGET=android_cocos_new_test
    #- os: linux
    #  env: BUILD_TARGET=linux_cocos_new_test
    #- os: osx
    #  env: BUILD_TARGET=ios_cocos_new_lua_test
    #  osx_image: xcode11
    #- os: osx
    #  env: BUILD_TARGET=ios_cocos_new_cpp_test
    #  osx_image: xcode11

script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh

jdk:
  - oraclejdk8

cache:
  bundler: true

notifications:
  email: false

# blocklist
branches:
  except:
  - v4
