matrix:
  include:
    # linux
    - os: linux
      dist: xenial
      env: 
        - BUILD_TARGET=linux 
        - GEN_BINDING_AND_COCOSFILE=true
      sudo: required
      language: cpp
    # mac_cmake
    - os: osx
      env: BUILD_TARGET=mac_cmake
      language: cpp
      osx_image: xcode10.3
      sudo: required
    # iOS_cmake
    - os: osx
      env: BUILD_TARGET=ios_cmake
      language: cpp
      osx_image: xcode11
      sudo: required
    # android cmake
    - os: linux
      env: BUILD_TARGET=android_cmake
      language: android
      sudo: required
      dist: xenial
    # android_lua cmake
    - os: linux
      env: BUILD_TARGET=android_lua_cmake
      language: android
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    # android_js cmake
    # - os: linux
    #   env: BUILD_TARGET=android_js_cmake
    #   language: android
    #   sudo: required
    - os: linux
      env: BUILD_TARGET=android_cocos_new_test
      language: android
      sudo: required
      dist: xenial
    - os: linux
      dist: xenial
      env: BUILD_TARGET=linux_cocos_new_test
      language: cpp
      sudo: required
    - os: osx
      env: BUILD_TARGET=ios_cocos_new_lua_test
      language: cpp
      osx_image: xcode11
      sudo: required
    - os: osx
      env: BUILD_TARGET=ios_cocos_new_cpp_test
      language: cpp
      osx_image: xcode11
      sudo: required

script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh

jdk:
  - oraclejdk8

cache:
  bundler: true

notifications:
  email: false

# blocklist
branches:
  except:
  - v4
