name: pull_request

on:
  pull_request:
    paths:
      - cmake/**/*
      - cocos/**/*
      - extensions/**/*
      - tests/**/*
      - thirdparty/**/*
      - CMakeLists.txt
      - .github/workflows/pr-ci.yml
      
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # Simple let github action to build all (TODO: optimize in the future)
  TRAVIS_PULL_REQUEST: true
  GITHUB_CI: true

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - x86
          - x64
    env:
      BUILD_TARGET: windows
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: 'true'
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Build
        run: tools\windows-ci\build.ps1 $env:BUILD_ARCH

  build-linux:
    name: build-linux
    runs-on: ubuntu-20.04
    env:
      TRAVIS_OS_NAME: linux
      BUILD_TARGET: linux
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: 'true'
      - name: Build
        run: |
          tools/travis-scripts/before-install.sh
          tools/travis-scripts/run-script.sh

  build-android:
    name: build-android
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch:
          - armeabi-v7a
          - arm64-v8a
          - x86
    env:
      TRAVIS_OS_NAME: linux
      BUILD_TARGET: android
      PYENV_VERSION: 2.7.18
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: 'true'
      - name: Build
        run: |
          tools/travis-scripts/before-install.sh
          tools/travis-scripts/run-script.sh

  build-osx:
    name: build-osx
    runs-on: macos-latest
    env:
      TRAVIS_OS_NAME: osx
      BUILD_TARGET: osx
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: 'true'
      - name: Build
        run: |
          tools/travis-scripts/before-install.sh
          tools/travis-scripts/run-script.sh
 
  build-ios:
    name: build-ios
    runs-on: macos-latest
    env:
      TRAVIS_OS_NAME: osx
      BUILD_TARGET: ios
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          lfs: 'true'
      - name: Build
        run: |
          tools/travis-scripts/before-install.sh
          tools/travis-scripts/run-script.sh
